/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3dpntrfillamentmeasurement;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Sparx
 */
public class tehMainGUI extends javax.swing.JFrame
{

    /**
     * Creates new form tehMainGUI
     */
    public tehMainGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabelItems = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMax = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelAvg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radioNone = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(1);
        jTextArea1.setText("Click here to start");
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea1FocusGained(evt);
            }
        });
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextArea1MouseReleased(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Number Of Items");

        jLabelItems.setText("0");

        jLabel3.setText("Min");

        jLabelMin.setText("0");

        jLabel5.setText("Max");

        jLabelMax.setText("0");

        jLabel7.setText("Average");

        jLabelAvg.setText("0");

        jLabel9.setText("Thanks<?>");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });

        jLabelStatus.setText("Status(Idle)");

        buttonGroup1.add(radio1);
        radio1.setText("1.XX");
        radio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radio1MouseReleased(evt);
            }
        });

        buttonGroup1.add(radio3);
        radio3.setText("3.XX");
        radio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radio3MouseReleased(evt);
            }
        });

        buttonGroup1.add(radioNone);
        radioNone.setSelected(true);
        radioNone.setText("NONE");
        radioNone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radioNoneMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(radio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioNone)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1)
                    .addComponent(radio3)
                    .addComponent(radioNone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMax)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelAvg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelStatus)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea1KeyTyped
    {//GEN-HEADEREND:event_jTextArea1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jTextArea1FocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTextArea1FocusGained
    {//GEN-HEADEREND:event_jTextArea1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextArea1FocusGained

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea1KeyReleased
    {//GEN-HEADEREND:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == 107)
        {
            Double in;
            //String tmp = new String("");
            try
            {
                //debugging
                //System.out.println("made it to try \n");
                this.jLabelStatus.setText("Working...");
                //this.jTextArea1.setText(this.jTextArea1.toString().replace("+", ""));
                this.jTextArea1.setText(this.jTextArea1.getText().replace("+", ""));
                //tmp = tmp.replace("+", "");
                in = Double.valueOf(this.jTextArea1.getText());
                tehLst.addItem(in);
                //here add start of next numnber, either 1. or 3. 
                if (this.radioNone.isSelected() == true)
                {this.jTextArea1.setText("");}
                if (this.radio1.isSelected() == true)
                {this.jTextArea1.setText("1.");}
                if (this.radio3.isSelected() == true)
                {this.jTextArea1.setText("3.");}
                //now populate
                this.jLabelItems.setText(tehLst.getLstLength() +"");
                this.jLabelMin.setText(tehLst.getMin() + "");
                this.jLabelMax.setText(tehLst.getMax() + "");
                this.jLabelAvg.setText(String.format("%.3f", tehLst.getAvg() ) + "");
                this.jLabelStatus.setText("Status(Idle)");
            } 
            catch (NumberFormatException e)
            {
                System.out.println("BAD Number Entered \n");
                this.jLabelStatus.setText("BAD Number!");
                this.jTextArea1.setText("");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel9MouseReleased
    {//GEN-HEADEREND:event_jLabel9MouseReleased
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, 
                  "Just a simple program i wrote for when i am getting the average\n"
                + "of faliment, feel free to use this for whatever you want\n"
                + "Instructions, enter number and press enter\n"
                + "The program will keep track of everything that is displayed\n"
                + "Works best with a num pad\n");
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jTextArea1MouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTextArea1MouseReleased
    {//GEN-HEADEREND:event_jTextArea1MouseReleased
        // TODO add your handling code here:
        //this.jTextArea1.setText("");
        //here add start of next numnber, either 1. or 3. 
                if (this.radioNone.isSelected() == true)
                {this.jTextArea1.setText("");}
                if (this.radio1.isSelected() == true)
                {this.jTextArea1.setText("1.");}
                if (this.radio3.isSelected() == true)
                {this.jTextArea1.setText("3.");}
                //now populate
    }//GEN-LAST:event_jTextArea1MouseReleased

    private void radio1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio1MouseReleased
        // TODO add your handling code here:
        //this.radio1.setSelected(true);
        
        this.jTextArea1.setText("1.");
    }//GEN-LAST:event_radio1MouseReleased

    private void radio3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio3MouseReleased
        // TODO add your handling code here:
        
        this.jTextArea1.setText("3.");
    }//GEN-LAST:event_radio3MouseReleased

    private void radioNoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioNoneMouseReleased
        // TODO add your handling code here:
        
        this.jTextArea1.setText("");
    }//GEN-LAST:event_radioNoneMouseReleased

    /**
     * @param args the command line arguments
     */
    public counterObjt tehLst = new counterObjt();

    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(tehMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(tehMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(tehMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(tehMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new tehMainGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAvg;
    private javax.swing.JLabel jLabelItems;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radioNone;
    // End of variables declaration//GEN-END:variables
}
